"""Module extensions for MLIR Tutorial dependencies."""

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def _llvm_deps_impl(_):
    """Implementation of the llvm_deps module extension."""
    LLVM_COMMIT = "11158cfe3faa2c9c04c8b5fdac3ac25eec75cb51"

    # Download LLVM/MLIR using a git repository
    new_git_repository(
        name = "llvm-raw",
        build_file_content = "# empty",
        commit = LLVM_COMMIT,
        init_submodules = False,
        remote = "https://github.com/llvm/llvm-project.git",
        patches = [
            # This patch file contains changes that are fixed in upstream LLVM
            # that are (usually) required to build HEIR, but are not included
            # as of the LLVM_COMMIT hash above (the fixes are still progressing
            # through the automated integration process). The patch file is
            # automatically generated, and should not be removed even if empty.
            "@heir//patches:llvm.patch",
        ],
        patch_args = ["-p1"],
    )

    # Optional LLVM dependencies for performance. Not required but the bazel
    # build has no way to omit them. See https://reviews.llvm.org/D143344#4232172
    maybe(
        http_archive,
        name = "llvm_zstd",
        build_file = "@llvm-raw//utils/bazel/third_party_build:zstd.BUILD",
        sha256 = "7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0",
        strip_prefix = "zstd-1.5.2",
        urls = [
            "https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz",
        ],
    )

    maybe(
        http_archive,
        name = "llvm_zlib",
        build_file = "@llvm-raw//utils/bazel/third_party_build:zlib-ng.BUILD",
        sha256 = "e36bb346c00472a1f9ff2a0a4643e590a254be6379da7cddd9daeb9a7f296731",
        strip_prefix = "zlib-ng-2.0.7",
        urls = [
            "https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.0.7.zip",
        ],
    )

llvm_deps = module_extension(
    implementation = _llvm_deps_impl,
)

def _veir_repository_impl(rctx):
    """Implementation of the veir_repository repository rule.

    VEIR is a formally verified, Lean-based MLIR-compatible optimizer used by
    the `--mod-arith-to-arith-veir` pass. Its `veir-opt` binary is not built
    by bazel: it is built out-of-band with `lake build` in the VEIR
    repository, which produces `.lake/build/bin/veir-opt`.

    This rule exposes that prebuilt binary as `@veir//:veir-opt`. The binary
    is discovered via the `HEIR_VEIR_OPT_PATH` environment variable (also
    settable with `--repo_env=HEIR_VEIR_OPT_PATH=...`). When the variable is
    unset or the file does not exist, the filegroup is empty, so builds still
    succeed and lit tests gated on the `veir` feature are skipped (see
    tests/lit.cfg.py).
    """
    veir_opt_path = rctx.os.environ.get("HEIR_VEIR_OPT_PATH", "")
    srcs = []
    if veir_opt_path and rctx.path(veir_opt_path).exists:
        rctx.symlink(veir_opt_path, "veir-opt-bin")
        srcs = ["veir-opt-bin"]
    rctx.file(
        "BUILD.bazel",
        content = """# Generated by veir_repository in @heir//bazel:extensions.bzl
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "veir-opt",
    srcs = {srcs},
)
""".format(srcs = srcs),
        executable = False,
    )

veir_repository = repository_rule(
    implementation = _veir_repository_impl,
    local = True,
    environ = ["HEIR_VEIR_OPT_PATH"],
    doc = "Exposes a prebuilt veir-opt binary (built out-of-band with " +
          "`lake build`) located via the HEIR_VEIR_OPT_PATH environment " +
          "variable.",
)
