package(
    default_applicable_licenses = ["@heir//:license"],
    default_visibility = ["//visibility:public"],
)

exports_files([
    "bison_macos_spawn_addchdir.patch",
    "fideslib_openfhe_compat.patch",
    "fideslib_openfhe_bazel.patch",
    "llvm.patch",
])
