// End-to-end dot product test using CHEDDAR GPU FHE backend.
// Mirrors tests/Examples/lattigo/ckks/dot_product_8f/dot_product_8f_test.go

#include <gtest/gtest.h>

#include <cmath>
#include <complex>
#include <cstdint>
#include <iostream>
#include <memory>
#include <vector>

#include "tests/Examples/cheddar/ckks/dot_product_8f/dot_product_lib.h"

using namespace cheddar;
using word = uint64_t;
using Complex = std::complex<double>;

TEST(CheddarDotProduct, EndToEnd) {
  std::cout << "=== CHEDDAR Dot Product 8f Test ===" << std::endl;

  // Parameters from the compiled MLIR's cheddar.Q / cheddar.P
  // (generated by --mlir-to-ckks=ciphertext-degree=32768)
  std::vector<word> main_primes = {
      36028797014376449ULL, 35184358850561ULL, 35184377331713ULL,
      35184363569153ULL,    35184376545281ULL, 35184365273089ULL,
      35184373006337ULL,    35184368025601ULL, 35184372744193ULL};
  std::vector<word> aux_primes = {
      1152921504614055937ULL, 1152921504615628801ULL, 1152921504616808449ULL};

  std::vector<std::pair<int, int>> level_config;
  for (int i = 1; i <= static_cast<int>(main_primes.size()); ++i) {
    level_config.push_back({i, 0});
  }

  int log_degree = 16;
  double base_scale = static_cast<double>(1ULL << 45);
  int default_encryption_level = static_cast<int>(main_primes.size()) - 1;

  std::cout << "[1/6] Creating context..." << std::flush;
  Parameter<word> param(log_degree, base_scale, default_encryption_level,
                        level_config, main_primes, aux_primes);
  auto context = Context<word>::Create(param);
  std::cout << " done" << std::endl;

  std::cout << "[2/6] Generating keys..." << std::flush;
  UserInterface<word> ui(context);
  // Rotation keys needed by the dot product (from compiled MLIR)
  for (int rot : {6, 7}) {
    ui.PrepareRotationKey(rot, default_encryption_level);
  }
  std::cout << " done" << std::endl;

  // Input vectors
  std::vector<double> arg0 = {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8};
  std::vector<double> arg1 = {0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9};
  double expected = 2.50;

  std::cout << "[3/6] Encrypting inputs..." << std::flush;
  auto& encoder = context->encoder_;
  auto ct0 = dot_product__encrypt__arg0(context, encoder, ui, arg0, ui);
  auto ct1 = dot_product__encrypt__arg1(context, encoder, ui, arg1, ui);
  std::cout << " done" << std::endl;

  std::cout << "[4/6] Computing dot product on GPU..." << std::flush;
  auto result_ct = dot_product(context, encoder, ui, ct0, ct1);
  std::cout << " done" << std::endl;

  std::cout << "[5/6] Decrypting..." << std::flush;
  double result =
      dot_product__decrypt__result0(context, encoder, ui, result_ct, ui);
  std::cout << " done" << std::endl;

  std::cout << "[6/6] Checking result..." << std::endl;
  std::cout << "  Expected: " << expected << std::endl;
  std::cout << "  Got:      " << result << std::endl;
  std::cout << "  Error:    " << std::abs(result - expected) << std::endl;

  EXPECT_NEAR(result, expected, 0.01)
      << "Dot product result doesn't match expected value";

  std::cout << "=== CHEDDAR Dot Product Test Complete ===" << std::endl;
}
