name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # pin@4.3.0

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8  # pin@v2.3.2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          generate_release_notes: true

  monitor-wheels:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      actions: read
      issues: write
    steps:
      - name: Wait for wheels workflow to complete
        id: wait_for_wheels
        uses: lewagon/wait-on-check-action@0dceb95e7c4cad8cc7422aee3885998f5cab9c79  # pin@v1.4.0
        with:
          ref: ${{ needs.create-release.outputs.tag_name }}
          check-name: 'pypi_upload'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 60
          allowed-conclusions: success,skipped,neutral
        continue-on-error: true

      - name: Create issue on failure
        if: steps.wait_for_wheels.outcome == 'failure'
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea  # pin@v7.0.1
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Wheels workflow failed for release ${{ needs.create-release.outputs.tag_name }}`,
              body: `The wheels workflow failed to complete successfully. Please check the workflow run for details: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            })
