name: Update TODO backlinks
on:
  push:
    branches:
      - main
jobs:
  insert-backlinks:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3
    - name: todo-backlinks
      uses: j2kun/todo-backlinks@12b447ef971f465feb2a7298a1240157e8712942 # pin@v0.0.5
      env:
        GITHUB_TOKEN: ${{ github.token }}
